backend:
  name: github
  branch: master 
  repo: nxnwtech/NXNW-tech-conference

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Subject", name: "subject", widget: "string"}
      - {label: "Job", name: "job", widget: "string"}
      - {label: "profileImage", name: "profileImage", widget: "image"}
      - {label: "Github", name: "github", widget: "string"}
      - {label: "Linkedin", name: "linkedin", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}

  - name: "callForProposalsIntro"
    label: "Call For Proposals"
    folder: "content/callForProposalsIntro"
    create: false
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Call For Proposals"}
      - {label: "Content", name: "content", widget: "markdown"}

  - name: "callToPapers"
    label: "Call To Papers"
    folder: "content/callToPapers"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - {label: "Track", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Track Image", name: "trackImage", widget: "image"}
      - label: callToPapersItem
        name: Item
        widget: list
        allow_add: true
        fields:
          - {label: Topic, name: topic, widget: string}

  - name: "schedule"
    label: "Schedule"
    folder: "content/schedule"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - {label: "Track", name: "name", widget: "string"}
      - label: scheduleItems
        name: Item
        widget: list
        allow_add: true
        fields:
          - {label: Talk, name: talk, widget: string}
          - {label: Time, name: time, widget: datetime, timeFormat: "HH:mm"}
          - {label: Duration, name: duration, widget: string}
          - {label: Venue, name: venue, widget: string}

  - name: "siteConfig"
    label: "Site Config"
    folder: "content/site-config"
    create: false
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Site Config"}
      - {label: "Show Call to Papers", name: "papers", widget: "boolean", default: true}
      - {label: "Show Speakers", name: "speakers", widget: "boolean", default: true}
      - {label: "Show Schedule", name: "schedule", widget: "boolean", default: true}

  - name: "about"
    label: "About"
    folder: "content/about"
    create: false
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "About"}
      - {label: "Content", name: "content", widget: "markdown"}

  - name: "codeOfConduct"
    label: "Code of Conduct"
    folder: "content/codeOfConduct"
    create: false
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Code of Conduct"}
      - {label: "Intro", name: "intro", widget: "markdown"}
      - {label: "Quick Title", name: "quickTitle", widget: "string", default: "The Quick Version"}
      - {label: "Quick Version", name: "quickVersion", widget: "markdown"}
      - {label: "Long Title", name: "longTitle", widget: "string", default: "The Less Quick Version"}
      - {label: "Long Version", name: "longVersion", widget: "markdown"}
      - {label: "Credits", name: "credits", widget: "markdown"}




